name: jigu

services:
  mongo:
    image: mongo:8.0.13-noble
    container_name: mongo
    ports:
      - 27017:27017
    networks:
      - server
    volumes:
      - ~/.container/jigu/mongo/data:/data/db
    environment:
      - TZ=Asia/Shanghai
      - MONGO_INITDB_DATABASE=jigu
      - MONGO_INITDB_ROOT_USERNAME=jigu
      - MONGO_INITDB_ROOT_PASSWORD=password

networks:
  server:
    driver: bridge
